/**
*   @file RheiaDockSystSettingsPanel.h
*
*   @author Nicolas Macherey (nm@graymat.fr)
*   @version 0.0.1
*   @date 17-November-2009
*/
#ifndef RheiaDockSystSettingsPanel_h_
#define RheiaDockSystSettingsPanel_h_

#include <RheiaBaseSettings.h>
#include <RheiaConfigurationPanel.h>
#include <wx/panel.h>
#include <wx/string.h>

/**
*   @class RheiaDockSystSettingsPanel
*
*   @brief This is the basic class for mamanging the docking systems settings
*
*   Mainly this panels load the docksystconf_panel.xrc file in order to allow the user
*   to manage Rheia's docking system configuration options.
*   The docking system is the wxAuiManager used to manage Rheia's main frame.
*   Here the user can configure the following options :
*
*       + Configure captions and gradient colors
*       + Configure text colours in the manager
*
*   @author Nicolas Macherey (nm@graymat.fr)
*   @version 0.0.1
*   @date 17-November-2009
*/
class BASE_DLLEXPORT RheiaDockSystSettingsPanel : public RheiaConfigurationPanel
{
public:
    /*******************************************************************************
    *   CONSTRUCTORS AND DESTRUCTORS
    *******************************************************************************/
    /**
    *   Basic constructor taking the parent in input.
    *   @param parent the parent window
    */
	RheiaDockSystSettingsPanel( wxWindow* parent );
	
	/** Default destructor */
	virtual ~RheiaDockSystSettingsPanel() {};

    /*******************************************************************************
    *   METHODS TO OVERLOAD
    *******************************************************************************/
	/**
	*   @see RheiaConfigurationPanel for more info
	*   @return the panel's title.
	*/
	virtual wxString GetTitle() const { return wxT("Docking System Settings"); };

	/**
	*   This method is used to get the bitmap base name for the configuration tool.
	*   @see RheiaConfigurationPanel for more info
	*
	*   @return the panel's bitmap base name. You must supply two bitmaps:
	*/
	virtual wxString GetBitmapBaseName() const;

	/**
	*   @see RheiaConfigurationPanel for more info
	*   @return If this method returns true the user's action will be validated.
	*/
	virtual bool OnApply();

	/**
	*   @see RheiaConfigurationPanel for more info
	*   @return This method shall simply returns true, if the configuration tool can
	*   be cancelled or false if it can't.
	*/
	virtual bool OnCancel();

protected :
    /*******************************************************************************
    *   PRIVATE MEMBERS
    *******************************************************************************/
    /**
    *   This method is used to initialize the default environment for this configuration
    *   tool. Basically it is loading the default informations from the configuration
    *   manager and the default user profile.
    */
    void DoInitEnvironment();

    /**
    *   This method is used to save the configuration options setted by the user
    *   it will store it's informations in application's general user configuration
    */
    void DoSaveEnvironment();

    /*******************************************************************************
    *   EVENTS CALLBACKS
    *******************************************************************************/
    /**
    *   This method is used when the user wants to change a button color (i.e : Aui colors )
    *   It will display the standard wxWidgets color picker dialog in order to allow the user
    *   to choose a specific color for the tool he wants to configure.
    *   @param event the wxCommandEvent generated by a pression on the options related button
    */
    void OnChooseColour(wxCommandEvent& event);

    /*******************************************************************************
    *   EVENTS TABLE
    *******************************************************************************/
    DECLARE_EVENT_TABLE()
};

#endif
